<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><!DOCTYPE hierarchy [        <!ELEMENT hierarchy (android.widget.FrameLayout)*>        <!ATTLIST hierarchy                index CDATA #REQUIRED                class CDATA #REQUIRED                rotation CDATA #REQUIRED                width CDATA #REQUIRED                height CDATA #REQUIRED>        <!ELEMENT android.widget.FrameLayout (android.widget.FrameLayout|android.widget.LinearLayout|android.view.ViewGroup|android.widget.RelativeLayout|android.widget.ImageView)*>        <!ATTLIST android.widget.FrameLayout                bounds CDATA #REQUIRED                checkable CDATA #REQUIRED                checked CDATA #REQUIRED                class CDATA #REQUIRED                clickable CDATA #REQUIRED                displayed CDATA #REQUIRED                enabled CDATA #REQUIRED                focusable CDATA #REQUIRED                focused CDATA #REQUIRED                index CDATA #REQUIRED                long-clickable CDATA #REQUIRED                package CDATA #REQUIRED                password CDATA #REQUIRED                resource-id CDATA #IMPLIED                scrollable CDATA #REQUIRED                selected CDATA #REQUIRED                text CDATA #REQUIRED>        <!ELEMENT android.widget.LinearLayout (android.widget.FrameLayout|android.widget.LinearLayout|android.widget.RelativeLayout|android.widget.TextView|android.view.View|androidx.viewpager.widget.ViewPager|android.widget.ImageView)*>        <!ATTLIST android.widget.LinearLayout                bounds CDATA #REQUIRED                checkable CDATA #REQUIRED                checked CDATA #REQUIRED                class CDATA #REQUIRED                clickable CDATA #REQUIRED                displayed CDATA #REQUIRED                enabled CDATA #REQUIRED                focusable CDATA #REQUIRED                focused CDATA #REQUIRED                index CDATA #REQUIRED                long-clickable CDATA #REQUIRED                package CDATA #REQUIRED                password CDATA #REQUIRED                resource-id CDATA #IMPLIED                scrollable CDATA #REQUIRED                selected CDATA #REQUIRED                text CDATA #REQUIRED>        <!ELEMENT android.view.ViewGroup (android.widget.FrameLayout|androidx.recyclerview.widget.RecyclerView)*>        <!ATTLIST android.view.ViewGroup                bounds CDATA #REQUIRED                checkable CDATA #REQUIRED                checked CDATA #REQUIRED                class CDATA #REQUIRED                clickable CDATA #REQUIRED                displayed CDATA #REQUIRED                enabled CDATA #REQUIRED                focusable CDATA #REQUIRED                focused CDATA #REQUIRED                index CDATA #REQUIRED                long-clickable CDATA #REQUIRED                package CDATA #REQUIRED                password CDATA #REQUIRED                resource-id CDATA #REQUIRED                scrollable CDATA #REQUIRED                selected CDATA #REQUIRED                text CDATA #REQUIRED>        <!ELEMENT android.widget.RelativeLayout (android.widget.EditText|android.widget.ImageView|android.widget.LinearLayout|android.view.ViewGroup|android.view.View|android.widget.TextView|android.widget.RelativeLayout|android.widget.FrameLayout)*>        <!ATTLIST android.widget.RelativeLayout                bounds CDATA #REQUIRED                checkable CDATA #REQUIRED                checked CDATA #REQUIRED                class CDATA #REQUIRED                clickable CDATA #REQUIRED                displayed CDATA #REQUIRED                enabled CDATA #REQUIRED                focusable CDATA #REQUIRED                focused CDATA #REQUIRED                index CDATA #REQUIRED                long-clickable CDATA #REQUIRED                package CDATA #REQUIRED                password CDATA #REQUIRED                resource-id CDATA #IMPLIED                scrollable CDATA #REQUIRED                selected CDATA #REQUIRED                text CDATA #REQUIRED>        <!ELEMENT android.widget.EditText (#PCDATA)>        <!ATTLIST android.widget.EditText                index CDATA #REQUIRED                package CDATA #REQUIRED                class CDATA #REQUIRED                text CDATA #REQUIRED                resource-id CDATA #REQUIRED                checkable CDATA #REQUIRED                checked CDATA #REQUIRED                clickable CDATA #REQUIRED                enabled CDATA #REQUIRED                focusable CDATA #REQUIRED                focused CDATA #REQUIRED                long-clickable CDATA #REQUIRED                password CDATA #REQUIRED                scrollable CDATA #REQUIRED                selected CDATA #REQUIRED                bounds CDATA #REQUIRED                displayed CDATA #REQUIRED>        <!ELEMENT android.widget.ImageView (#PCDATA)>        <!ATTLIST android.widget.ImageView                bounds CDATA #REQUIRED                checkable CDATA #REQUIRED                checked CDATA #REQUIRED                class CDATA #REQUIRED                clickable CDATA #REQUIRED                displayed CDATA #REQUIRED                enabled CDATA #REQUIRED                focusable CDATA #REQUIRED                focused CDATA #REQUIRED                index CDATA #REQUIRED                long-clickable CDATA #REQUIRED                package CDATA #REQUIRED                password CDATA #REQUIRED                resource-id CDATA #IMPLIED                scrollable CDATA #REQUIRED                selected CDATA #REQUIRED                text CDATA #REQUIRED>        <!ELEMENT android.widget.TextView (#PCDATA)>        <!ATTLIST android.widget.TextView                bounds CDATA #REQUIRED                checkable CDATA #REQUIRED                checked CDATA #REQUIRED                class CDATA #REQUIRED                clickable CDATA #REQUIRED                displayed CDATA #REQUIRED                enabled CDATA #REQUIRED                focusable CDATA #REQUIRED                focused CDATA #REQUIRED                index CDATA #REQUIRED                long-clickable CDATA #REQUIRED                package CDATA #REQUIRED                password CDATA #REQUIRED                resource-id CDATA #IMPLIED                scrollable CDATA #REQUIRED                selected CDATA #REQUIRED                text CDATA #REQUIRED>        <!ELEMENT android.view.View (#PCDATA)>        <!ATTLIST android.view.View                bounds CDATA #REQUIRED                checkable CDATA #REQUIRED                checked CDATA #REQUIRED                class CDATA #REQUIRED                clickable CDATA #REQUIRED                displayed CDATA #REQUIRED                enabled CDATA #REQUIRED                focusable CDATA #REQUIRED                focused CDATA #REQUIRED                index CDATA #REQUIRED                long-clickable CDATA #REQUIRED                package CDATA #REQUIRED                password CDATA #REQUIRED                resource-id CDATA #IMPLIED                scrollable CDATA #REQUIRED                selected CDATA #REQUIRED                text CDATA #REQUIRED>        <!ELEMENT androidx.viewpager.widget.ViewPager (android.widget.RelativeLayout)*>        <!ATTLIST androidx.viewpager.widget.ViewPager                index CDATA #REQUIRED                package CDATA #REQUIRED                class CDATA #REQUIRED                text CDATA #REQUIRED                resource-id CDATA #REQUIRED                checkable CDATA #REQUIRED                checked CDATA #REQUIRED                clickable CDATA #REQUIRED                enabled CDATA #REQUIRED                focusable CDATA #REQUIRED                focused CDATA #REQUIRED                long-clickable CDATA #REQUIRED                password CDATA #REQUIRED                scrollable CDATA #REQUIRED                selected CDATA #REQUIRED                bounds CDATA #REQUIRED                displayed CDATA #REQUIRED>        <!ELEMENT androidx.recyclerview.widget.RecyclerView (android.widget.LinearLayout)*>        <!ATTLIST androidx.recyclerview.widget.RecyclerView                index CDATA #REQUIRED                package CDATA #REQUIRED                class CDATA #REQUIRED                text CDATA #REQUIRED                resource-id CDATA #REQUIRED                checkable CDATA #REQUIRED                checked CDATA #REQUIRED                clickable CDATA #REQUIRED                enabled CDATA #REQUIRED                focusable CDATA #REQUIRED                focused CDATA #REQUIRED                long-clickable CDATA #REQUIRED                password CDATA #REQUIRED                scrollable CDATA #REQUIRED                selected CDATA #REQUIRED                bounds CDATA #REQUIRED                displayed CDATA #REQUIRED>        ]><hierarchy index="0" class="hierarchy" rotation="0" width="1080" height="2030">  <android.widget.FrameLayout index="0" package="com.xueqiu.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,2030]" displayed="true">    <android.widget.FrameLayout index="0" package="com.xueqiu.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,2030]" displayed="true">      <android.widget.LinearLayout index="0" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,2030]" displayed="true">        <android.widget.FrameLayout index="0" package="com.xueqiu.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,2030]" displayed="true">          <android.view.ViewGroup index="0" package="com.xueqiu.android" class="android.view.ViewGroup" text="" resource-id="com.xueqiu.android:id/decor_content_parent" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,2030]" displayed="true">            <android.widget.FrameLayout index="0" package="com.xueqiu.android" class="android.widget.FrameLayout" text="" resource-id="android:id/content" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1080,2030]" displayed="true">              <android.widget.LinearLayout index="1" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,76][1080,2030]" displayed="true">                <android.widget.LinearLayout index="0" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,76][1080,208]" displayed="true">                  <android.widget.RelativeLayout index="0" package="com.xueqiu.android" class="android.widget.RelativeLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[8,76][930,208]" displayed="true">                    <android.widget.EditText index="0" package="com.xueqiu.android" class="android.widget.EditText" text="����Ͱ�" resource-id="com.xueqiu.android:id/search_input_text" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" long-clickable="true" password="false" scrollable="false" selected="false" bounds="[30,98][908,186]" displayed="true" />                    <android.widget.ImageView index="1" package="com.xueqiu.android" class="android.widget.ImageView" text="" resource-id="com.xueqiu.android:id/action_delete_text" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[811,100][894,183]" displayed="true" />                  </android.widget.RelativeLayout>                  <android.widget.TextView index="1" package="com.xueqiu.android" class="android.widget.TextView" text="ȡ��" resource-id="com.xueqiu.android:id/action_close" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[930,76][1080,208]" displayed="true" />                </android.widget.LinearLayout>                <android.widget.RelativeLayout index="1" package="com.xueqiu.android" class="android.widget.RelativeLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,208][1080,2030]" displayed="true">                  <android.widget.LinearLayout index="0" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" resource-id="com.xueqiu.android:id/ll_search_result" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,208][1080,2030]" displayed="true">                    <android.widget.FrameLayout index="0" package="com.xueqiu.android" class="android.widget.FrameLayout" text="" resource-id="com.xueqiu.android:id/ti_tab_indicator" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,208][1080,318]" displayed="true">                      <android.widget.FrameLayout index="0" package="com.xueqiu.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,208][1080,318]" displayed="true">                        <android.widget.FrameLayout index="0" package="com.xueqiu.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,208][1080,318]" displayed="true">                          <android.widget.LinearLayout index="0" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" resource-id="com.xueqiu.android:id/indicator_container" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,208][1080,318]" displayed="true">                            <android.view.View index="0" package="com.xueqiu.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,208][1080,318]" displayed="true" />                          </android.widget.LinearLayout>                          <android.widget.LinearLayout index="1" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" resource-id="com.xueqiu.android:id/title_container" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,208][1080,318]" displayed="true">                            <android.widget.TextView index="0" package="com.xueqiu.android" class="android.widget.TextView" text="�ۺ�" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,208][270,318]" displayed="true" />                            <android.widget.TextView index="1" package="com.xueqiu.android" class="android.widget.TextView" text="��Ʊ" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[270,208][540,318]" displayed="true" />                            <android.widget.TextView index="2" package="com.xueqiu.android" class="android.widget.TextView" text="�û�" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[540,208][810,318]" displayed="true" />                            <android.widget.TextView index="3" package="com.xueqiu.android" class="android.widget.TextView" text="���" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[810,208][1080,318]" displayed="true" />                          </android.widget.LinearLayout>                        </android.widget.FrameLayout>                      </android.widget.FrameLayout>                    </android.widget.FrameLayout>                    <androidx.viewpager.widget.ViewPager index="1" package="com.xueqiu.android" class="androidx.viewpager.widget.ViewPager" text="" resource-id="com.xueqiu.android:id/vp_view_pager" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="true" selected="false" bounds="[0,318][1080,2030]" displayed="true">                      <android.widget.RelativeLayout index="0" package="com.xueqiu.android" class="android.widget.RelativeLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,318][1080,2030]" displayed="true">                        <android.view.ViewGroup index="0" package="com.xueqiu.android" class="android.view.ViewGroup" text="" resource-id="com.xueqiu.android:id/layout_refresh" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,318][1080,2030]" displayed="true">                          <androidx.recyclerview.widget.RecyclerView index="1" package="com.xueqiu.android" class="androidx.recyclerview.widget.RecyclerView" text="" resource-id="com.xueqiu.android:id/list" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="true" selected="false" bounds="[0,318][1080,2030]" displayed="true">                            <android.widget.LinearLayout index="0" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,318][1080,794]" displayed="true">                              <android.widget.LinearLayout index="0" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,318][1080,794]" displayed="true">                                <android.widget.LinearLayout index="0" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" resource-id="com.xueqiu.android:id/ll_stock_result_view" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,318][1080,678]" displayed="true">                                  <android.view.View index="0" package="com.xueqiu.android" class="android.view.View" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,318][1080,319]" displayed="true" />                                  <android.widget.LinearLayout index="1" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" resource-id="com.xueqiu.android:id/ll_stock_item_container" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,319][1080,649]" displayed="true">                                    <android.widget.FrameLayout index="0" package="com.xueqiu.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,319][1080,484]" displayed="true">                                      <android.widget.RelativeLayout index="0" package="com.xueqiu.android" class="android.widget.RelativeLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,319][1080,484]" displayed="true">                                        <android.widget.LinearLayout index="0" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" resource-id="com.xueqiu.android:id/stock_layout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[33,348][655,454]" displayed="true">                                          <android.widget.TextView index="0" package="com.xueqiu.android" class="android.widget.TextView" text="����Ͱ�" resource-id="com.xueqiu.android:id/stockName" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[33,348][209,407]" displayed="true" />                                          <android.widget.LinearLayout index="1" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[33,410][172,454]" displayed="true">                                            <android.widget.ImageView index="0" package="com.xueqiu.android" class="android.widget.ImageView" text="" resource-id="com.xueqiu.android:id/stock_type_icon" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[33,415][72,448]" displayed="true" />                                            <android.widget.TextView index="1" package="com.xueqiu.android" class="android.widget.TextView" text="BABA" resource-id="com.xueqiu.android:id/stockCode" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[86,410][172,454]" displayed="true" />                                          </android.widget.LinearLayout>                                        </android.widget.LinearLayout>                                        <android.widget.LinearLayout index="1" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" resource-id="com.xueqiu.android:id/price_layout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[655,353][874,450]" displayed="true">                                          <android.widget.TextView index="0" package="com.xueqiu.android" class="android.widget.TextView" text="194.00" resource-id="com.xueqiu.android:id/current_price" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[710,353][830,406]" displayed="true" />                                          <android.widget.TextView index="1" package="com.xueqiu.android" class="android.widget.TextView" text="+4.81%" resource-id="com.xueqiu.android:id/change_percentage" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[721,406][830,450]" displayed="true" />                                        </android.widget.LinearLayout>                                        <android.widget.LinearLayout index="2" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" resource-id="com.xueqiu.android:id/add_attention" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[874,365][1047,437]" displayed="true">                                          <android.widget.TextView index="0" package="com.xueqiu.android" class="android.widget.TextView" text="����ѡ" resource-id="com.xueqiu.android:id/follow_btn" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[874,365][1047,437]" displayed="true" />                                        </android.widget.LinearLayout>                                        <android.view.View index="3" package="com.xueqiu.android" class="android.view.View" text="" resource-id="com.xueqiu.android:id/divider" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,483][1080,484]" displayed="true" />                                      </android.widget.RelativeLayout>                                    </android.widget.FrameLayout>                                    <android.widget.FrameLayout index="1" package="com.xueqiu.android" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,484][1080,649]" displayed="true">                                      <android.widget.RelativeLayout index="0" package="com.xueqiu.android" class="android.widget.RelativeLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,484][1080,649]" displayed="true">                                        <android.widget.LinearLayout index="0" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" resource-id="com.xueqiu.android:id/stock_layout" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[33,513][666,619]" displayed="true">                                          <android.widget.TextView index="0" package="com.xueqiu.android" class="android.widget.TextView" text="����Ͱ�-SW" resource-id="com.xueqiu.android:id/stockName" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[33,513][286,572]" displayed="true" />                                          <android.widget.LinearLayout index="1" package="com.xueqiu.android" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[33,575][181,619]" displayed="true">                                            <android.widget.ImageView index="0" package="com.xueqiu.android" class="android.widget.ImageView" text="" resource-id="com.xueqiu.android:id/stock_type_icon" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[33,580][72,613]" displa